server:
  port: 80


eureka:
  client:
    register-with-eureka: true             #表示是否将自己注册进eurekaserver 默认为true
    fetch-registry: true                 #是否从eureka抓取已注册的服务信息，默认为true，集训必须开启，才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
#指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
#指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.atguigu.springcloud.service.PaymentFeignService: debug
spring:
  application:
    name: openFeign-service
